### ISSUE TITLE
cooking

### ISSUE THREAD

**Issue by dotnwat** [smfrpc/smf-getting-started-cpp#1]
is the result of the new cmake build infrastructure that projects like this will be better off adopting smf as an ingredient?

**Comment by emaxerrno** [comment]
yeah. I'm trying to figure it out too. 

https://github.com/hakuch/CMakeCooking/issues/6

**Comment by emaxerrno** [comment]
I'm learning cmake as we go. But i think you need a `project-config.cmake` per project

**Comment by emaxerrno** [comment]
@noahdesu do you know?

**Comment by emaxerrno** [comment]
i think there are 2 ways. you can do it as a submodule and then it should work, but i have - honestly - no clue. I mostly am playing whackamole w/ cmake at this point. 

I think i follow now but there is no easy to follow guide on how to make one's project cmake-consumable by downstream projects.

**Comment by emaxerrno** [comment]
also i have no clue how to debug when an ingredient fails. 

https://github.com/hakuch/CMakeCooking/issues/7

**Comment by emaxerrno** [comment]
@noahdesu  i put a wip on https://github.com/smfrpc/smf-getting-started-cpp/pull/2

**Comment by emaxerrno** [comment]
@noahdesu aparently cmake segfaults too. 
![cmake_segfault](https://user-images.githubusercontent.com/175206/51012160-c9809380-1529-11e9-9819-429d323fa1bf.png)

**Comment by emaxerrno** [comment]
@noahdesu  - i checked in a working version of the code w/ all recipes included.

**Comment by emaxerrno** [comment]
https://github.com/smfrpc/smf-getting-started-cpp working now. see build status. I also added travis to this.
