### ISSUE TITLE
run "./build.sh" failed

### ISSUE THREAD

**Issue by bluealert** [smfrpc/smf-getting-started-cpp#4]
Ubuntu 18.04

```
CMake Error at src/CMakeLists.txt:15 (add_executable):
Target "demo_client" links to target "flatbuffers::flatbuffers" but the
target was not found. Perhaps a find_package() call is missing for an
IMPORTED target, or an ALIAS target is missing?
```

Cooking: Installed the following ingredients:
  - fmt
  - ragel
  - Protobuf
  - hwloc
  - Zstd
  - zlib
  - numactl
  - Boost
  - GnuTLS
  - smf
  - yaml-cpp
  - Googletest
  - cryptopp
  - xxHash
  - dpdk
  - Hdrhistogram
  - colm
  - Flatbuffers
  - GFlags
  - gmp
  - lksctp-tools
  - Seastar
  - libpciaccess
  - Glog
  - Googlebenchmark
  - c-ares
  - nettle
  - lz4

-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   thread
--   unit_test_framework
--   system
--   chrono
--   date_time
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found c-ares: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libcares.so (found suitable version "1.13.0", minimum required is "1.13") 
-- Found cryptopp: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libcryptopp.so (Required is at least version "5.6.5") 
-- Found dpdk: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/include/dpdk  
-- Found lz4: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/liblz4.so (found suitable version "1.8.0", minimum required is "1.8.0") 
-- Looking for LZ4_compress_default
-- Looking for LZ4_compress_default - found
-- Performing Test Concepts_FOUND
-- Performing Test Concepts_FOUND - Success
-- Found GnuTLS: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libgnutls.so (found suitable version "3.5.18", minimum required is "3.5.18") 
-- Performing Test LinuxMembarrier_FOUND
-- Performing Test LinuxMembarrier_FOUND - Success
-- Found Protobuf: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libprotobuf.so;-lpthread (found suitable version "3.3.0", minimum required is "3.3.0") 
-- Performing Test Sanitizers_ADDRESS_FOUND
-- Performing Test Sanitizers_ADDRESS_FOUND - Success
-- Performing Test Sanitizers_UNDEFINED_BEHAVIOR_FOUND
-- Performing Test Sanitizers_UNDEFINED_BEHAVIOR_FOUND - Success
-- Performing Test Sanitizers_FIBER_SUPPORT
-- Performing Test Sanitizers_FIBER_SUPPORT - Success
-- Found Sanitizers: -fsanitize=address  
-- Performing Test StdAtomic_EXPLICIT_LINK
-- Performing Test StdAtomic_EXPLICIT_LINK - Success
-- Found StdAtomic: -latomic  
-- Performing Test StdFilesystem_NO_EXPLICIT_LINK
-- Performing Test StdFilesystem_NO_EXPLICIT_LINK - Failed
-- Performing Test StdFilesystem_STDCXXFS_LIBRARY
-- Performing Test StdFilesystem_STDCXXFS_LIBRARY - Success
-- Found StdFilesystem: stdc++fs  
-- Found hwloc: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libhwloc.so (found suitable version "1.11.5", minimum required is "1.11.5") 
-- Found lksctp-tools: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libsctp.so  
-- Found numactl: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libnuma.so  
-- Found rt: -lrt  
-- Found yaml-cpp: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libyaml-cpp.a (found suitable version "0.5.3", minimum required is "0.5.3") 
-- Found xxHash: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/include (found version "") 
-- Found Flatbuffers: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libflatbuffers.a (found version "") 
-- Found Zstd: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libzstd.a (found version "1.3.8") 
-- Found Hdrhistogram: /home/tao/Cpp/smf-getting-started-cpp/build/_cooking/installed/lib/libhdr_histogram_static.a  
-- Configuring done
CMake Error at src/CMakeLists.txt:15 (add_executable):
  Target "demo_client" links to target "flatbuffers::flatbuffers" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at src/CMakeLists.txt:10 (add_executable):
  Target "demo_server" links to target "flatbuffers::flatbuffers" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at src/CMakeLists.txt:15 (add_executable):
  Target "demo_client" links to target "flatbuffers::flatbuffers" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at src/CMakeLists.txt:10 (add_executable):
  Target "demo_server" links to target "flatbuffers::flatbuffers" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/tao/Cpp/smf-getting-started-cpp/build

**Comment by emaxerrno** [comment]
@bluealert Good point. 

Thanks for catching. We moved to a much simpler cmake config and I forgot to update this.  

I will push a *much* improved cmake from the upstream `smf` project today.

**Comment by emaxerrno** [comment]
@bluealert  - can you give the PR in #3  a run. It should work. There is no more cooking or anything, a simple cmake proj. 

We'll merge that in a bit.

**Comment by emaxerrno** [comment]
@bluealert  - everything is working in master now w/ the latest seastar & all. 

Give it a spin.

**Comment by emaxerrno** [comment]
hey @bluealert  - did you try this? let me know if it worked for you.

**Comment by bluealert** [comment]
yes, it worked for me! @senior7515

**Comment by emaxerrno** [comment]
@bluealert  - awesome! let me know if you run into any issues.
